/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.10.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {}
export type ExecuteMsg = ("remove_hash" | "clear_queue") | {
  add_led_hash: {
    hash: Uint256;
  };
};
export type Uint256 = string;
export type QueryMsg = "get_hash_list";
export interface HashListResponse {
  hashes: Uint256[];
}